keys:
  - &master_yubikey age1... # TODO: fill in master age public key
  - &host_nas age1...       # TODO: fill in NAS's age public key

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *master_yubikey
        - *host_nas

