# The "keys" dictionary defines variables (aliases) for PUBLIC KEYS only.
# SOPS uses these public keys to encrypt data.
keys:
  - &host_freebsd_userg_ssh_pubkey XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  - &host_nas_age_pubkey age1...?????????? what here?

# The "creation_rules" tell SOPS which public keys to use for encryption.
creation_rules:
  # This rule applies to any file whose name exactly matches "secrets.yaml"
  - path_regex: secrets.yaml$

    # The "key_groups" dictionary defines WHO is allowed to decrypt the file.
    # EVERY host or admin public key listed in this specific key_group will
    # be able to decrypt ALL the secrets inside "secrets.yaml".
    key_groups:
      - pgp:
          - *host_freebsd_userg_ssh_pubkey
        age:
          - *host_nas_age_pubkey

